
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-happycows-m23-10am-1
owner: ucsb-cs156-m23
repo_name: proj-happycows-m23-10am-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMDI3NTY4","is_bot":false,"login":"haostevewu","name":"Hao Wu"},"headRefName":"Hao-LeaderboardBackButton","number":18,"title":"Hao - add back button and test for it for leaderboard","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-1/pull/18"},{"author":{"id":"U_kgDOBXjmyQ","is_bot":false,"login":"ZixiaoJin","name":""},"headRefName":"ZixiaoJin-Currency","number":16,"title":"#8 total wealth displayed as currency","url":"https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-1/pull/16"}]
